# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  pull_request:
    paths:
      - '.github/workflows/main.yml'
      - 'src/**'

  push:
    paths:
      - '.github/workflows/main.yml'
      - 'src/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      #Executa o Lint
      #- name: arduino/arduino-lint-action
      #  uses: arduino/arduino-lint-action@v1.0.0
      #Executa Arduino CLI
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1

# We then install the platform, which one will be determined
      # dynamically by the build matrix.
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
 
      # Finally, we compile the sketch, using the FQBN that was set
      # in the build matrix.
      - name: Compile Sketch
        run: arduino-cli compile --fqbn arduino:avr:uno ./src
