# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  pull_request:
    paths:
      - '.github/workflows/main.yml'
      - 'src/**'

  push:
    paths:
      - '.github/workflows/main.yml'
      - 'src/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      #Executa o Lint
      #- name: arduino/arduino-lint-action
      #  uses: arduino/arduino-lint-action@v1.0.0
      
      #Executa Arduino CLI
      - name: A Preparar Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1

# We then install the platform, which one will be determined
      # dynamically by the build matrix.
      - name: Instala platforma
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
          
      # Instala bibliotecas do Arduino Base   
      #- name: Instala bibliotecas
      #  run: |
      #    arduino-cli lib install "Servo"
       
  #Copia as bibliotecas da pasta bibliotecas
      - name: Instala bibliotecas da pasta bibliotecas
        run: |
          mkdir -p "$HOME/Arduino/libraries"
          ln -s "$PWD/bibliotecas" "$HOME/Arduino/libraries/."    
         
  
      # Finally, we compile the sketch, using the FQBN that was set
      # in the build matrix.
      #- name: Compilar Sketch
      #  run: arduino-cli compile --fqbn arduino:avr:uno ./src
# Compile all *.ino files for the Arduino Uno
      - name: Compilar Sketch independente nome ficheiro
        run: | 
          cd $GITHUB_WORKSPACE
          for f in **/*.ino ; do
          arduino-cli compile -b arduino:avr:uno $f

          done
          
      - name: Compilar Sketch2
        run: arduino-cli compile --fqbn arduino:avr:uno ./src/*.ino
      - name: Compilar Sketch3
        run: arduino-cli compile --fqbn arduino:avr:uno ./src/*-src.ino            
            
